# Generated by Django 4.1 on 2022-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_text', models.CharField(max_length=255)),
                ('invoice_created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
