# Generated by Django 4.1 on 2022-09-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_attached_table',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_object_id',
            new_name='object_id',
        ),
    ]
