# Generated by Django 4.1 on 2022-09-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0002_rename_comment_attached_table_comment_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': ['comment_created_at']},
        ),
    ]
