# Generated by Django 4.1 on 2022-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0004_comment_comment_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
